= Docker setup

Corpora are compiled and served using
https://github.com/KIParla/NoSketch-Engine-Docker[KIParla/NoSketch-Engine-Docker],
which in turn builds on
https://github.com/ELTE-DH/NoSketch-Engine-Docker[NoSketch-Engine-Docker].

== 1. Install Docker

Download and install https://www.docker.com/get-started/[Docker Desktop] for your platform.

== 2. Clone KIParla/NoSketch-Engine-Docker

[source,bash]
----
git clone https://github.com/KIParla/NoSketch-Engine-Docker.git
cd NoSketch-Engine-Docker
make pull
----

== 3. Link the corpora directory

Symlink this repository as the `corpora/` directory inside the runtime repo:

[source,bash]
----
ln -s /path/to/KIParla/KIParla-NoSketch-Data NoSketch-Engine-Docker/corpora
----

Alternatively, copy the files directly:

[source,bash]
----
cp -r /path/to/KIParla/KIParla-NoSketch-Data/* NoSketch-Engine-Docker/corpora/
----

Before compiling, make sure all vertical files have been generated.
See xref:generate.adoc[Generating vertical files].

== 4. Compile corpora

From inside the `NoSketch-Engine-Docker` directory, compile all corpora listed in `corpora/registry/`:

[source,bash]
----
make compile
----

To compile a single corpus (and overwrite existing index):

[source,bash]
----
make execute CMD="compilecorp --no-ske --recompile-corpus KIP"
----

== 5. Run

[source,bash]
----
make run
----

Navigate to http://localhost:10070 to use the interface.

== Corpus paths

Registry files use the following path conventions inside the Docker container:

[cols="1,2"]
|===
| Setting | Path pattern

| `PATH` (compiled index)
| `/corpora/CORPUS/indexed/`

| `VERTICAL` (source file)
| `/corpora/CORPUS/vertical/source`
|===

These paths are already set correctly in all registry files under `registry/`.
